server:
  port: 10000
  servlet:
    session:
      tracking-modes: COOKIE
      cookie:
        http-only: true
        secure: false
        same-site: lax

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.179.241:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: app
    password: 1234
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: 43.200.179.241
      port: 6379


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.app.domain;com.example.app.dto
  configuration:
    map-underscore-to-camel-case: true