services:
  app:
    build: .
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring        # DB 자동 생성
      MYSQL_USER: spring            # 사용자 생성
      MYSQL_PASSWORD: 1234